project:
  type: website

website:
  title: "Homepage"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: https://alonsosilvaallende.github.io/blog/
        text: Blog
      - href: https://alonsosilvaallende.github.io/til/
        text: TIL
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/alonsosilvaallende
      - icon: twitter
        href: https://twitter.com/alonsosilva


format:
  html:
    theme: 
      dark: darkly
      light: cosmos
    css: styles.css
    toc: true



